version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://fraud_user:fraud_pass@db:5432/fraud_db
      - PROJECT_NAME="Cloud-Based Credit Card Fraud Detection System"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./ml/model:/app/ml/model
      - ./frontend:/app/frontend

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=fraud_user
      - POSTGRES_PASSWORD=fraud_pass
      - POSTGRES_DB=fraud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fraud_user -d fraud_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
